CREATE TABLE Queue(
ID NUMBER primary key,
NAME VARCHAR2(50) NOT NULL,
DETAILS VARCHAR2(200),
MODIFIED_DATE TIMESTAMP(2) NOT NULL
);

CREATE TABLE TASK(
ID NUMBER primary key,
NAME VARCHAR2(50) NOT NULL,
DETAILS VARCHAR2(200),
OWNER VARCHAR2(20),
FROM_QUEUE VARCHAR2(50),
TO_QUEUE VARCHAR2(50),
ASSIGNED VARCHAR2(20),
STATUS VARCHAR2(20),
MODIFIED_DATE TIMESTAMP(2) NOT NULL
);
